# Generated by Django 5.1 on 2024-08-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('endereco', models.CharField(max_length=300, null=True)),
                ('username', models.CharField(max_length=11, null=True, verbose_name='username')),
            ],
        ),
    ]
