# Generated by Django 5.1 on 2024-09-01 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaCursos',
            fields=[
                ('idCaCursos', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CaServicos',
            fields=[
                ('idCaServicos', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('idMetodoPagamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=300)),
                ('username', models.CharField(max_length=11, null=True, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('valor_cur', models.CharField(max_length=100)),
                ('fk_idCaCursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.cacursos')),
                ('fk_idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idAgendamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(help_text='Formato em YYYY-MM-DD')),
                ('hora', models.TimeField(help_text='Formato em HH-MM-SS')),
                ('fk_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.curso')),
                ('fk_idMetodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('idNotaFiscal', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('dataEmissao', models.DateTimeField(auto_now_add=True)),
                ('fk_idMetodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('idComprovante', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fk_Agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.agendamento')),
                ('fk_idNotaFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.notafiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idServico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('valor_ser', models.CharField(max_length=100)),
                ('fk_idCaServicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.caservicos')),
                ('fk_idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.funcionario')),
            ],
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fk_idServico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.servico'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='fk_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.usuario'),
        ),
    ]
