# Generated by Django 5.1.1 on 2024-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacursos',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
