# Generated by Django 5.1 on 2024-08-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='endereco',
        ),
    ]
