# Generated by Django 5.1 on 2024-09-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='fk_idCaServicos',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='fk_idFuncionario',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='fk_idServico',
        ),
        migrations.DeleteModel(
            name='CaServicos',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
    ]
