# Generated by Django 5.1.1 on 2024-09-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0002_alter_cacursos_image_alter_curso_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacursos',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
