# Generated by Django 5.1 on 2024-08-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0003_categoria_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='categoria',
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=200)),
                ('fk_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.categoria')),
            ],
        ),
    ]
