# Generated by Django 5.1 on 2024-09-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0003_remove_agendamento_data_hora_remove_agendamento_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='dias',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_final',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='valor_cur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
