# Generated by Django 5.1 on 2024-09-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0004_curso_dias_curso_hora_final_curso_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='dias',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
