# Generated by Django 5.1 on 2024-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0004_rename_nome_categoria_categoria_entrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='fk_idCategoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
