# Generated by Django 5.0.7 on 2024-09-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0004_alter_cacursos_image_alter_curso_image'),
        ('BStudios', '0005_alter_curso_dias'),
    ]

    operations = [
    ]
