# Generated by Django 5.1 on 2024-08-30 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0005_subcategoria_remove_entrada_fk_idcategoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFuncionario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=11)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('valor_cur', models.CharField(max_length=100)),
                ('fk_idSubcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.subcategoria')),
                ('fk_idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('idServico', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('valor_ser', models.CharField(max_length=100)),
                ('fk_idFuncionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.funcionario')),
                ('fk_idSubcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.subcategoria')),
            ],
        ),
    ]
