# Generated by Django 5.1 on 2024-08-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0006_funcionario_curso_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('idMetodoPagamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('idAgendamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(help_text='Formato em YYYY-MM-DD')),
                ('hora', models.TimeField(help_text='Formato em HH-MM-SS')),
                ('fk_idCurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.curso')),
                ('fk_idServico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.servico')),
                ('fk_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.usuario')),
                ('fk_idMetodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('idNotaFiscal', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=100)),
                ('dataEmissao', models.DateTimeField(auto_now_add=True)),
                ('fk_idMetodoPagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.metodopagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('idComprovante', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('fk_Agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.agendamento')),
                ('fk_idNotaFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.notafiscal')),
            ],
        ),
    ]
