# Generated by Django 5.1 on 2024-08-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0007_metodopagamento_agendamento_notafiscal_comprovante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategoria',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='fk_idSubcategoria',
            new_name='fk_idCategoria',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='fk_idSubcategoria',
            new_name='fk_idCategoria',
        ),
    ]
