# Generated by Django 5.1 on 2024-08-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0008_rename_subcategoria_categoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='CategoriaCur',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='fk_idCategoria',
            new_name='fk_idCategoriaCur',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='fk_idCategoria',
            new_name='fk_idCategoriaSer',
        ),
    ]
