# Generated by Django 5.1 on 2024-08-30 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0009_rename_categoria_categoriacur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='servico',
            name='fk_idCategoriaSer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BStudios.categoriaser'),
        ),
    ]
