# Generated by Django 5.1 on 2024-08-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BStudios', '0010_categoriaser_alter_servico_fk_idcategoriaser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaCur',
            new_name='CaCursos',
        ),
        migrations.RenameModel(
            old_name='CategoriaSer',
            new_name='CaServicos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='fk_idCategoriaCur',
            new_name='fk_idCaCursos',
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='fk_idCategoriaSer',
            new_name='fk_idCaServicos',
        ),
    ]
